import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy | Voice the Line",
  description: "How Voice the Line handles microphone access and browser recordings.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return <main className="legal-page"><header className="legal-header"><Link className="wordmark" href="/" title="Voice the Line home"><span className="wordmark-mark">V</span><span className="wordmark-name">VOICE THE LINE</span><b>CUE STUDIO</b></Link><Link className="legal-back" href="/" title="Back to the Voice the Line studio">Back to studio</Link></header><article className="legal-content"><span className="section-kicker">Privacy</span><h1>Your voice stays with you.</h1><p className="legal-updated">Last updated: <time dateTime="2026-08-30">August 30, 2026</time></p><p>Voice the Line is a browser-based voice over game. This page describes the data handling in the current version of the site.</p><h2>Microphone access</h2><p>Recording is optional. If you choose to record, your browser asks for microphone permission. The site uses that permission only to create your local take.</p><h2>Voice recordings</h2><p>Your recording is kept in the browser during your session and is not uploaded to Voice the Line servers. When you export a take, your browser downloads a WebM file to your device.</p><h2>Accounts and analytics</h2><p>The current version does not require an account. The site uses Google Analytics 4 to measure page visits and basic feature usage, such as scene selection, playback, recording starts, and take exports.</p><h2>Analytics data</h2><p>Google Analytics may use cookies or similar browser storage and process technical usage information such as pages visited, device and browser details, and approximate location. The site does not send microphone recordings, recorded audio, or the contents of your takes to Google Analytics. We configure the tag to avoid advertising features and anonymize IP handling.</p><h2>Third-party services</h2><p>The site is delivered through Cloudflare Pages. Your browser may also request fonts from Google Fonts and the Google Analytics tag from Google services.</p><h2>Browser controls</h2><p>You can limit cookies and site storage through your browser settings. Analytics behavior may change when those browser controls are enabled.</p><h2>Contact</h2><p>For questions about this policy, contact the site owner through the <a href="https://github.com/joanjiaocn-rgb/voicetheline/issues" title="Voice the Line GitHub contact and issues">GitHub issue tracker</a>.</p></article><footer className="site-footer legal-footer"><div><strong>VOICE THE LINE</strong><span>Original scenes for your next take.</span></div><nav aria-label="Footer navigation"><Link href="/privacy" title="Read the Voice the Line privacy policy">Privacy</Link><Link href="/terms" title="Read the Voice the Line terms">Terms</Link></nav></footer></main>;
}
