import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms | Voice the Line",
  description: "Terms for using the Voice the Line browser voice over game.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return <main className="legal-page"><header className="legal-header"><Link className="wordmark" href="/" title="Voice the Line home"><span className="wordmark-mark">V</span><span className="wordmark-name">VOICE THE LINE</span><b>CUE STUDIO</b></Link><Link className="legal-back" href="/" title="Back to the Voice the Line studio">Back to studio</Link></header><article className="legal-content"><span className="section-kicker">Terms</span><h1>Use the studio, make your take.</h1><p className="legal-updated">Last updated: <time dateTime="2026-08-30">August 30, 2026</time></p><p>By using Voice the Line, you agree to use the site lawfully and respectfully. These terms apply to the current browser-based version of the service.</p><h2>Use of the site</h2><p>You may use the original scenes and recording tools for personal practice, creative experimentation, and other lawful purposes. Do not attempt to disrupt the site or use it to record people without appropriate permission.</p><h2>Your recordings</h2><p>You control recordings made with your microphone. Voice the Line does not upload or claim ownership of your local takes. You are responsible for the content you record and share.</p><h2>Original scene materials</h2><p>The scripts, interface, and original scene assets are provided for use inside the Voice the Line experience. Do not represent them as your own or redistribute them as a separate stock library without permission.</p><h2>Availability</h2><p>The site is provided as a free tool and may change as the project develops. Browser microphone support, local recording formats, and download behavior can vary by device and browser.</p><h2>Questions</h2><p>For questions about these terms, contact the site owner through the <a href="https://github.com/joanjiaocn-rgb/voicetheline/issues" title="Voice the Line GitHub contact and issues">GitHub issue tracker</a>.</p></article><footer className="site-footer legal-footer"><div><strong>VOICE THE LINE</strong><span>Original scenes for your next take.</span></div><nav aria-label="Footer navigation"><Link href="/privacy" title="Read the Voice the Line privacy policy">Privacy</Link><Link href="/terms" title="Read the Voice the Line terms">Terms</Link></nav></footer></main>;
}
